// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doabpodnyscrftrlydyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvYWJwb2RueXNjcmZ0cmx5ZHl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzY5NjUsImV4cCI6MjA3NDcxMjk2NX0.2DpWv2TKQH1cLncJ2J3didFyMYiEIylenpF-n_jfPmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});